<?php
function h($id,$t,$c,$s,$tag="h2"){return ["id"=>$id,"elType"=>"widget","widgetType"=>"heading","settings"=>["title"=>$t,"header_size"=>$tag,"align"=>"center","title_color"=>$c,"typography_typography"=>"custom","typography_font_family"=>"Playfair Display","typography_font_size"=>["unit"=>"px","size"=>$s],"typography_font_weight"=>"700"],"elements"=>[]];}
function t($id,$html){return ["id"=>$id,"elType"=>"widget","widgetType"=>"text-editor","settings"=>["editor"=>$html],"elements"=>[]];}

$s1 = ["id"=>"p1","elType"=>"section","settings"=>["background_background"=>"classic","background_color"=>"#FAF6EC","padding"=>["unit"=>"px","top"=>"112","right"=>"16","bottom"=>"0","left"=>"16","isLinked"=>false],"gap"=>"no"],"elements"=>[["id"=>"p1c","elType"=>"column","settings"=>["_column_size"=>100],"elements"=>[t("p1e",'<p style="font-size:12px; letter-spacing:0.22em; text-transform:uppercase; font-weight:600; color:#B0603F; text-align:center;">Партнёрство</p>'),h("p1t","Кого мы ищем?","#2F4A33",48),t("p1tx",'<p style="text-align:center; max-width:768px; margin:32px auto 0; font-size:18px; line-height:1.7; color:#2B2620;">Мы открыты к партнёрству с инвесторами, предпринимателями и компаниями, заинтересованными в создании долгосрочного проекта на основе исторического наследия.</p>'),h("p1o","Что мы предлагаем:","#2F4A33",30),t("p1l",'<div style="max-width:600px; margin:24px auto 0;"><div style="display:flex; align-items:flex-start; gap:16px; margin-bottom:16px;"><span style="display:inline-block; width:8px; height:8px; background:#B8963E; transform:rotate(45deg); margin-top:10px; flex-shrink:0;"></span><span style="font-size:18px; line-height:1.6; color:#2B2620;">Участие в уникальном историко-культурном проекте.</span></div><div style="display:flex; align-items:flex-start; gap:16px; margin-bottom:16px;"><span style="display:inline-block; width:8px; height:8px; background:#B8963E; transform:rotate(45deg); margin-top:10px; flex-shrink:0;"></span><span style="font-size:18px; line-height:1.6; color:#2B2620;">Формирование команды единомышленников.</span></div><div style="display:flex; align-items:flex-start; gap:16px; margin-bottom:16px;"><span style="display:inline-block; width:8px; height:8px; background:#B8963E; transform:rotate(45deg); margin-top:10px; flex-shrink:0;"></span><span style="font-size:18px; line-height:1.6; color:#2B2620;">Создание устойчивого агро-туристического кластера с долгосрочной перспективой.</span></div></div>')]]]];

$s2 = ["id"=>"p2","elType"=>"section","settings"=>["background_background"=>"classic","background_color"=>"#FAF6EC","padding"=>["unit"=>"px","top"=>"48","right"=>"16","bottom"=>"112","left"=>"16","isLinked"=>false],"gap"=>"no"],"elements"=>[["id"=>"p2c","elType"=>"column","settings"=>["_column_size"=>100],"elements"=>[t("p2n",'<div style="background:#2F4A33; border-top:4px solid #B8963E; padding:32px; max-width:600px; margin:0 auto;"><p style="font-size:18px; font-style:italic; line-height:1.6; color:#F5EFE3; margin-bottom:24px;">Все условия сотрудничества, включая финансовые модели, доли участия и конкретные сроки, обсуждаются строго индивидуально на личной встрече.</p><div style="border-top:1px solid rgba(184,150,62,0.3); padding-top:24px;"><p style="font-size:16px; line-height:1.6; color:#F5EFE3;">Мы создаём закрытый клуб единомышленников, где каждое решение принимается осознанно и с учётом взаимных интересов.</p></div></div>')]]]];

$export = ["content"=>[$s1,$s2], "title"=>"Partners", "type"=>"section"];
file_put_contents("/var/www/html/partners-native.json", json_encode($export, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT));
echo "OK: ".strlen(json_encode($export))." bytes\n";